#!/usr/bin/env bash

# *This file is meant to be run as root or with sudo*
# It will backup the Postgres database to the local server

# confirm that use is root or sudo, if not exit
if [ "$EUID" -ne 0 ]
  then echo "Please run as root or with sudo"
  exit
fi

# Get the directory of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# Get the dir 1 level up
DIR="$(dirname "$DIR")"

# Load the environment variables
source "$DIR/.env"

REQUIRED_VARS=(
  LOCAL_BACKUP_PATH
  LOCAL_POSTGRES_BACKUP_PATH
  LOGS_PATH
)

for var in "${REQUIRED_VARS[@]}"; do
  if [ -z "${!var}" ] || [ "${!var}" = "REPLACE_ME" ]; then
    echo "$var is unset. Please set this in your .env file." 
    exit 1
  fi
done

# log file + backup path
LOG_FILE="${LOGS_PATH}plausible-backup-postgres.log"
BACKUP_PATH=${LOCAL_BACKUP_PATH}${LOCAL_POSTGRES_BACKUP_PATH}

# function to log messages
log_message() {
  local log_dir=$(dirname "$LOG_FILE")
  local log_file=$(basename "$LOG_FILE")
  local timestamp=$(date +"%Y-%m-%d %H:%M:%S")
  local message="${1//[$'\n']/}" # Remove newline characters from the message
  local level="${2:-INFO}" # Optional log level

  # Create the log directory if it doesn't exist
  if [ ! -d "$log_dir" ]; then
    mkdir -p "$log_dir"
  fi

  # Create the log file if it doesn't exist
  if [ ! -f "$LOG_FILE" ]; then
    touch "$LOG_FILE"
  fi

  echo "$timestamp - [$level] $message" >> "$LOG_FILE"
}

# Create the local backup directory if is does not exist
mkdir -p ${BACKUP_PATH}

# create a timestamp variable
timestamp=$(date +%Y-%m-%d-%H-%M-%S)

# Define the container name
# Look for POSTGRES_CONTAINER_NAME and set to default if not found
if [ -z ${POSTGRES_CONTAINER_NAME+x} ]; then
    POSTGRES_CONTAINER_NAME="analytics-plausible_db-1"
fi

CONTAINER_NAME=${POSTGRES_CONTAINER_NAME}

# Look for env LOCAL_BACKUP_RETENTION_DAYS and set default if not found
if [ -z ${LOCAL_BACKUP_RETENTION_DAYS+x} ]; then
    LOCAL_BACKUP_RETENTION_DAYS=7
fi

docker exec $CONTAINER_NAME /bin/bash -c "mkdir -p /var/lib/postgresql/backups/ && PGPASSWORD=postgres pg_dump -h localhost -p 5432 -U postgres -F t -b -v -f /var/lib/postgresql/backups/plausible_db_backup_${timestamp}.tar plausible_db"

# Copy the backup file from Docker container to the server
log_message "Copying the backup file, plausible_db_backup_${timestamp}.tar, from Docker container to the local backup directory."
docker cp $CONTAINER_NAME:/var/lib/postgresql/backups/plausible_db_backup_${timestamp}.tar ${BACKUP_PATH}

# Remove the backup file from inside the Docker container
log_message "Removing the backup file, plausible_db_backup_${timestamp}.tar, from inside the Docker container."
docker exec $CONTAINER_NAME /bin/bash -c "rm /var/lib/postgresql/backups/plausible_db_backup_${timestamp}.tar"

log_message 'Pruning old Plausible Primary database backups to max age of '${LOCAL_BACKUP_RETENTION_DAYS}' days.'
find ${BACKUP_PATH} -type f -mtime +${LOCAL_BACKUP_RETENTION_DAYS} -exec rm {} \;

# change the ownership of the created backup files to the specified user
log_message "Changing the ownership of the created backup files to the ${LOCAL_USER:forge} user."
chown -R ${LOCAL_USER:forge}:${LOCAL_GROUP:forge} ${LOCAL_BACKUP_PATH}

# check for success
if [ $? -eq 0 ]; then
    log_message "Successfully backed up the Plausible Primary database to ${LOCAL_BACKUP_PATH}${LOCAL_POSTGRES_PATH}."
else
    log_message "Failed to backup the Plausible Primary database." "ERROR"
    exit 1
fi
